enum{
	GIGUI_UNKNOWN,
	GIGUI_HMENU_FILE,
	GIGUI_HMENU_VIEW,
	GIGUI_HMENU_HELP,

	GIGUI_MENU_PROJECT_NEW,
	GIGUI_MENU_PROJECT_OPEN,
	GIGUI_MENU_PROJECT_SAVE,
	GIGUI_MENU_PROJECT_SAVEAS,
	GIGUI_MENU_MODULE_DRILL
};